#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024–2026 Tomshley LLC
#
# GitLab runner image build targets.
# Run from: repo-root/gitlab/ (or via root Makefile: make gitlab-build)
#
# Shared variables and targets are provided by common/make/bake-targets.mk.
# Only platform-specific overrides need to be set here.

BAKE_FILE := docker-bake.hcl
BUILDX_NAME := cicd_pipelines_gitlab_buildx

include ../common/make/bake-targets.mk
