stages:
  - .pre
  - security.pre-build
  - build
  - test
  - security.post-build
  - deploy
  - .post

constraints:
  - "security.pre-build BEFORE build"
  - "build BEFORE test"
  - "test BEFORE security.post-build"
  - "security.post-build BEFORE deploy"
